apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster                   
metadata:
  # Name of cluster example tkg-cluster-01
  name: scaletest-7-xsmall                      
  # vSphere Workload Management Nameapace to deploy cluster to
  namespace: scale                       
spec:
  distribution:
    version: v1.20.2+vmware.1-tkg.1.1d4f79a                             
  topology:
    controlPlane:
      # Number of Nodes in Controlplane
      count: 1                                 
      #
      class: best-effort-xsmall               
      #vSphere storage class to use get this from vsphere admin  
      storageClass: vsphere-with-kubernetes 
    workers:
      #
      count: 1                
      #                 
      class: best-effort-xsmall     
      #vSphere storage class to use get this from vsphere admin
      storageClass: vsphere-with-kubernetes 